name: Push Test
on:
  push:
    branches:
      - main

jobs:
  lint-job:
    name: Lint Job
    runs-on: ubuntu-latest
    env:
      MY_VAR: Hi there! My name is
      FIRST_NAME: Mona
      MIDDLE_NAME: The
      LAST_NAME: Octocat
    steps:
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
